# server配置
server:
  port: 8080
  servlet:
    context-path: /
    #连接池配置

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/mavenspringboot
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

#mybaitsplus配置

mybatis-plus:
  type-aliases-package: com.city.pojo
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: idDeleted #进行逻辑删除
      table-prefix: news_ #pojo类可以忽略前缀

#jwt配置
jwt:
  token:
    tokenExpiration: 120 #有效时间,单位分钟
    tokenSignKey: headline123456  #当前程序签名秘钥 自定义